[project]
name = "medical-help-ai-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dotenv>=0.9.9",
    "fastapi>=0.120.2",
    "langchain>=1.0.2",
    "langgraph>=1.0.1",
    "psycopg2>=2.9.11",
]
